/**
 * HTML Exporter
 */

import { ComponentInstance, ExportConfig, ExportFile, ExportResult } from './types';
import { formatHTML, countLines } from './code-formatter';

export class HTMLExporter {
  async export(components: ComponentInstance[], config: ExportConfig): Promise<ExportResult> {
    const files: ExportFile[] = [];
    
    // Generate single HTML file
    const htmlFile = await this.generateHTML(components, config);
    files.push(htmlFile);
    
    // Generate inline CSS if needed
    if (config.includeTailwind) {
      const cssFile = this.generateTailwindCSS();
      files.push(cssFile);
    }
    
    return {
      files,
      metadata: {
        componentCount: components.length,
        totalLines: files.reduce((sum, f) => sum + countLines(f.content), 0),
        dependencies: [],
        format: 'html',
        timestamp: Date.now(),
      },
    };
  }
  
  private async generateHTML(components: ComponentInstance[], config: ExportConfig): Promise<ExportFile> {
    const head = this.generateHead(config);
    const body = components.map(c => this.componentToHTML(c)).join('\n\n');
    
    const html = `<!DOCTYPE html>
<html lang="en">
${head}
<body class="min-h-screen">
${body}
</body>
</html>`;
    
    return {
      path: 'index.html',
      content: await formatHTML(html),
      type: 'component',
    };
  }
  
  private generateHead(config: ExportConfig): string {
    return `<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${config.projectName}</title>
  ${config.includeTailwind ? '<script src="https://cdn.tailwindcss.com"></script>' : ''}
  ${config.includeComments ? '<!-- Generated by Conversational Product Designer -->' : ''}
</head>`;
  }
  
  private componentToHTML(comp: ComponentInstance): string {
    switch (comp.name) {
      case 'HeroSection':
      case 'HeroSplit':
        return this.heroToHTML(comp.props);
      case 'FeatureGrid':
      case 'FeatureList':
        return this.featuresToHTML(comp.props);
      case 'PricingTable':
      case 'PricingCompact':
        return this.pricingToHTML(comp.props);
      case 'CallToAction':
      case 'CTABanner':
        return this.ctaToHTML(comp.props);
      case 'Testimonials':
        return this.testimonialsToHTML(comp.props);
      case 'FAQ':
        return this.faqToHTML(comp.props);
      case 'Stats':
      case 'StatsMinimal':
        return this.statsToHTML(comp.props);
      default:
        return this.genericToHTML(comp.props);
    }
  }
  
  private heroToHTML(props: any): string {
    const colorScheme = props.colorScheme || 'blue';
    return `<section class="py-20 px-4 bg-gradient-to-br from-${colorScheme}-600 to-${colorScheme}-800">
  <div class="max-w-4xl mx-auto text-center">
    <h1 class="text-5xl font-bold text-white mb-6">
      ${this.escapeHTML(props.headline || 'Welcome')}
    </h1>
    <p class="text-xl text-${colorScheme}-100 mb-8">
      ${this.escapeHTML(props.subheadline || '')}
    </p>
    <div class="flex gap-4 justify-center">
      ${props.ctaText || props.primaryButton?.text ? `
      <button class="px-8 py-3 bg-white text-${colorScheme}-600 rounded-lg font-semibold hover:bg-gray-100">
        ${this.escapeHTML(props.ctaText || props.primaryButton?.text || 'Get Started')}
      </button>` : ''}
      ${props.secondaryButton?.text ? `
      <button class="px-8 py-3 border-2 border-white text-white rounded-lg font-semibold hover:bg-white/10">
        ${this.escapeHTML(props.secondaryButton.text)}
      </button>` : ''}
    </div>
  </div>
</section>`;
  }
  
  private featuresToHTML(props: any): string {
    const features = props.features || [];
    const featuresHTML = features.map((feature: any) => `
    <div class="text-center">
      ${feature.icon ? `<div class="text-4xl mb-4">${feature.icon}</div>` : ''}
      <h3 class="text-xl font-semibold mb-2">${this.escapeHTML(feature.title || 'Feature')}</h3>
      <p class="text-gray-600">${this.escapeHTML(feature.description || '')}</p>
    </div>`).join('');
    
    return `<section class="py-16 px-4">
  <div class="max-w-6xl mx-auto">
    ${props.title ? `<h2 class="text-3xl font-bold text-center mb-12">${this.escapeHTML(props.title)}</h2>` : ''}
    <div class="grid md:grid-cols-${props.columns || 3} gap-8">
      ${featuresHTML}
    </div>
  </div>
</section>`;
  }
  
  private pricingToHTML(props: any): string {
    const tiers = props.tiers || props.plans || [];
    const tiersHTML = tiers.map((tier: any) => `
    <div class="p-8 bg-white rounded-xl shadow-lg ${tier.highlighted ? 'ring-2 ring-blue-600' : ''}">
      <h3 class="text-2xl font-bold mb-2">${this.escapeHTML(tier.name || 'Plan')}</h3>
      <div class="text-4xl font-bold mb-4">
        ${this.escapeHTML(tier.price || '$0')}
        ${tier.period ? `<span class="text-lg text-gray-600">/${this.escapeHTML(tier.period)}</span>` : ''}
      </div>
      ${tier.features && tier.features.length > 0 ? `
      <ul class="space-y-3 mb-8">
        ${tier.features.map((f: string) => `
        <li class="flex items-center">
          <span class="mr-2">✓</span>
          ${this.escapeHTML(f)}
        </li>`).join('')}
      </ul>` : ''}
      <button class="w-full py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700">
        ${this.escapeHTML(tier.ctaText || 'Get Started')}
      </button>
    </div>`).join('');
    
    return `<section class="py-16 px-4 bg-gray-50">
  <div class="max-w-6xl mx-auto">
    ${props.title ? `<h2 class="text-3xl font-bold text-center mb-12">${this.escapeHTML(props.title)}</h2>` : ''}
    <div class="grid md:grid-cols-${tiers.length || 3} gap-8">
      ${tiersHTML}
    </div>
  </div>
</section>`;
  }
  
  private ctaToHTML(props: any): string {
    return `<section class="py-16 px-4 bg-blue-600">
  <div class="max-w-4xl mx-auto text-center">
    <h2 class="text-4xl font-bold text-white mb-4">
      ${this.escapeHTML(props.headline || props.text || 'Get Started Today')}
    </h2>
    ${props.description || props.secondaryText ? `
    <p class="text-xl text-blue-100 mb-8">
      ${this.escapeHTML(props.description || props.secondaryText || '')}
    </p>` : ''}
    <div class="flex gap-4 justify-center">
      ${props.buttonText || props.primaryButton?.text ? `
      <button class="px-8 py-3 bg-white text-blue-600 rounded-lg font-semibold hover:bg-gray-100">
        ${this.escapeHTML(props.buttonText || props.primaryButton?.text || 'Get Started')}
      </button>` : ''}
      ${props.secondaryButton?.text ? `
      <button class="px-8 py-3 border-2 border-white text-white rounded-lg font-semibold hover:bg-white/10">
        ${this.escapeHTML(props.secondaryButton.text)}
      </button>` : ''}
    </div>
  </div>
</section>`;
  }
  
  private testimonialsToHTML(props: any): string {
    const testimonials = props.testimonials || [];
    const testimonialsHTML = testimonials.map((t: any) => `
    <div class="p-6 bg-white rounded-xl shadow-lg">
      <div class="flex items-center mb-4">
        ${t.avatar ? `<img src="${t.avatar}" alt="${this.escapeHTML(t.name || 'User')}" class="w-12 h-12 rounded-full mr-4" />` : ''}
        <div>
          <div class="font-semibold">${this.escapeHTML(t.name || 'Anonymous')}</div>
          <div class="text-sm text-gray-600">${this.escapeHTML(t.role || '')}</div>
        </div>
      </div>
      <p class="text-gray-700 mb-4">${this.escapeHTML(t.content || '')}</p>
      ${t.rating ? `<div class="text-yellow-400">${'★'.repeat(t.rating)}</div>` : ''}
    </div>`).join('');
    
    return `<section class="py-16 px-4">
  <div class="max-w-6xl mx-auto">
    ${props.title ? `<h2 class="text-3xl font-bold text-center mb-12">${this.escapeHTML(props.title)}</h2>` : ''}
    <div class="grid md:grid-cols-3 gap-8">
      ${testimonialsHTML}
    </div>
  </div>
</section>`;
  }
  
  private faqToHTML(props: any): string {
    const questions = props.faqs || props.questions || [];
    const questionsHTML = questions.map((q: any, i: number) => `
    <details class="border border-gray-200 rounded-lg">
      <summary class="p-4 font-semibold cursor-pointer">
        ${this.escapeHTML(q.question || 'Question')}
      </summary>
      <div class="p-4 pt-0 text-gray-600">
        ${this.escapeHTML(q.answer || '')}
      </div>
    </details>`).join('');
    
    return `<section class="py-16 px-4">
  <div class="max-w-3xl mx-auto">
    ${props.title ? `<h2 class="text-3xl font-bold text-center mb-12">${this.escapeHTML(props.title)}</h2>` : ''}
    <div class="space-y-4">
      ${questionsHTML}
    </div>
  </div>
</section>`;
  }
  
  private statsToHTML(props: any): string {
    const stats = props.stats || [];
    const statsHTML = stats.map((stat: any) => `
    <div class="text-center">
      <div class="text-5xl font-bold text-blue-600 mb-2">
        ${this.escapeHTML(stat.value || '0')}
      </div>
      <div class="text-xl font-semibold mb-1">${this.escapeHTML(stat.label || '')}</div>
      ${stat.description ? `<div class="text-gray-600">${this.escapeHTML(stat.description)}</div>` : ''}
    </div>`).join('');
    
    return `<section class="py-16 px-4 bg-gray-50">
  <div class="max-w-6xl mx-auto">
    ${props.title ? `<h2 class="text-3xl font-bold text-center mb-12">${this.escapeHTML(props.title)}</h2>` : ''}
    <div class="grid md:grid-cols-${stats.length || 3} gap-8">
      ${statsHTML}
    </div>
  </div>
</section>`;
  }
  
  private genericToHTML(props: any): string {
    return `<section class="py-16 px-4">
  <div class="max-w-6xl mx-auto">
    <pre>${this.escapeHTML(JSON.stringify(props, null, 2))}</pre>
  </div>
</section>`;
  }
  
  private generateTailwindCSS(): ExportFile {
    return {
      path: 'styles.css',
      content: `/* Tailwind CSS is loaded via CDN in the HTML file */
/* Add custom styles here if needed */
`,
      type: 'style',
    };
  }
  
  private escapeHTML(text: string): string {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }
}
