/**
 * FeatureGrid Component
 * Generated by Conversational Product Designer
 */


import React from 'react';

interface FeatureGridProps {
  title: string;
  features: { title: string; description: string; icon: string }[];
  columns: string;
  colorScheme: string;
  style: string;
}

export default function FeatureGrid1(props: FeatureGrid1Props) {
  return (
    <section className="py-16 px-4">
      <div className="max-w-6xl mx-auto">
        {props.title && (
          <h2 className="text-3xl font-bold text-center mb-12">
            {props.title}
          </h2>
        )}
        <div className="grid md:grid-cols-2 gap-8">
          {props.features.map((feature: any, index: number) => (
            <div key={index} className="text-center">
              {feature.icon && (
                <div className="text-4xl mb-4">{feature.icon}</div>
              )}
              <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
