/**
 * HeroSplit Component
 * Generated by Conversational Product Designer
 */


import React from 'react';

interface HeroSplitProps {
  headline: string;
  subheadline: string;
  ctaText: string;
  ctaLink: string;
  image: string;
  features: string[];
  colorScheme: string;
}

export default function HeroSplit0(props: HeroSplit0Props) {
  return (
    <section className="py-20 px-4 bg-gradient-to-br from-indigo-600 to-indigo-800">
      <div className="max-w-4xl mx-auto text-center">
        <h1 className="text-5xl font-bold text-white mb-6">
          {props.headline}
        </h1>
        <p className="text-xl text-indigo-100 mb-8">
          {props.subheadline}
        </p>
        <div className="flex gap-4 justify-center">
          <button className="px-8 py-3 bg-white text-indigo-600 rounded-lg font-semibold hover:bg-gray-100">
            {props.primaryButton.text}
          </button>
          {props.secondaryButton && (
            <button className="px-8 py-3 border-2 border-white text-white rounded-lg font-semibold hover:bg-white/10">
              {props.secondaryButton.text}
            </button>
          )}
        </div>
      </div>
    </section>
  );
}
