/**
 * PricingTable Component
 * Generated by Conversational Product Designer
 */


import React from 'react';

interface PricingTableProps {
  title: string;
  tiers: { name: string; price: string; period: string; features: string[]; highlighted: boolean; ctaText: string }[];
  colorScheme: string;
  layout: string;
}

export default function PricingTable2(props: PricingTable2Props) {
  return (
    <section className="py-16 px-4 bg-gray-50">
      <div className="max-w-6xl mx-auto">
        {props.title && (
          <h2 className="text-3xl font-bold text-center mb-12">
            {props.title}
          </h2>
        )}
        <div className="grid md:grid-cols-3 gap-8">
          {props.tiers.map((tier: any, index: number) => (
            <div 
              key={index} 
              className={`p-8 bg-white rounded-xl shadow-lg ${tier.highlighted ? 'ring-2 ring-blue-600' : ''}`}
            >
              <h3 className="text-2xl font-bold mb-2">{tier.name}</h3>
              <div className="text-4xl font-bold mb-4">
                {tier.price}
                {tier.period && <span className="text-lg text-gray-600">/{tier.period}</span>}
              </div>
              <ul className="space-y-3 mb-8">
                {tier.features.map((feature: string, i: number) => (
                  <li key={i} className="flex items-center">
                    <span className="mr-2">✓</span>
                    {feature}
                  </li>
                ))}
              </ul>
              <button className="w-full py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700">
                {tier.ctaText || 'Get Started'}
              </button>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
